SRC += edwardkopp.c

LTO_ENABLE = yes

MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no

NKRO_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
MOUSEKEY_ENABLE = no
MOUSE_SHARED_EP = no
EXTRAKEY_ENABLE = yes
UNICODE_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

LEADER_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no

KEY_OVERRIDE_ENABLE = no

BLUETOOTH_ENABLE = no
OLED_DRIVER_ENABLE = no

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
