name: Build QMK firmware

on:
  push:
    branches:
      - main
    paths:
      - 'keyboards/**'
      - 'users/**'
      - 'qmk.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: edwardkopp/qmk_firmware
      qmk_ref: master

  tagging:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.generate-tag.outputs.tag}}
    steps:
      - name: Generate Tag String
        id: generate-tag
        run: echo "tag=$(date +%Y.%m.%d)" >> "$GITHUB_OUTPUT"

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs:
      - build
      - tagging
    with:
      release_name: ${{needs.tagging.outputs.tag}}
